-- =====================================================================
-- Quiniela FIFA 2026 — Esquema Supabase (tablas + RLS) consolidado
-- =====================================================================
-- Para reproducir el backend en un Supabase nuevo (ej. fork Tecology):
-- correr este archivo completo en el SQL Editor. Es idempotente
-- (CREATE ... IF NOT EXISTS / DROP POLICY IF EXISTS).
--
-- NOTA DE SEGURIDAD: la app es estática y usa solo la ANON KEY (sin backend
-- ni Supabase Auth). Por eso las operaciones de admin se hacen con la misma
-- anon key y las políticas de escritura/borrado son abiertas a `anon`. Esto
-- es un RIESGO ACEPTADO para uso corporativo cerrado (ver AUDITORIA_SEGURIDAD.md
-- hallazgos 3.1/3.6/3.9/3.10/3.11). Para producción pública: migrar a Auth
-- (rol admin) o Edge Functions y cerrar estas políticas.
-- =====================================================================

-- ---------- TABLAS ----------

create table if not exists public.participantes (
  id        bigint generated by default as identity primary key,
  nombre    text,
  alias     text,
  email     text,
  tel       text,
  codigo    text,
  favorito  text,
  fecha     timestamptz default now()
);

create table if not exists public.codigos_participante (
  id        bigint generated by default as identity primary key,
  codigo    text unique,
  usado     boolean default false,
  fecha     timestamptz default now()
);

create table if not exists public.quinielas (
  id              bigint generated by default as identity primary key,
  participante_id bigint references public.participantes(id),
  predicciones    jsonb,
  bracket         jsonb,
  goleador        text,
  campeon         text,
  puntos          integer default 0,
  fecha           timestamptz default now()
);
create unique index if not exists quinielas_participante_id_key on public.quinielas(participante_id);

create table if not exists public.resultados_reales (
  id            bigint generated by default as identity primary key,
  partido_idx   integer,
  resultado     text,
  goles_local   integer default 0,
  goles_visita  integer default 0,
  ganador       text,
  fecha         timestamptz default now()
);
create unique index if not exists resultados_reales_partido_idx_key on public.resultados_reales(partido_idx);

create table if not exists public.configuracion (
  id                   bigint generated by default as identity primary key,
  fecha_cierre         timestamptz,   -- gancho maestro global
  fecha_cierre_grupos  timestamptz,   -- 1era ronda
  fecha_cierre_r32     timestamptz,
  fecha_cierre_r16     timestamptz,
  fecha_cierre_qf      timestamptz,
  fecha_cierre_sf      timestamptz,
  fecha_cierre_final   timestamptz,
  permitir_edicion     boolean default true,
  admin_password       text           -- TODO: guardar solo hash (ver auditoría 3.6)
);

create table if not exists public.configuracion_visual (
  id     bigint generated by default as identity primary key,
  clave  text unique,
  valor  text
);

-- NOTA: este repo también usa `clasificados` y la vista `ranking_view`.
-- Su DDL exacto no está documentado; exportarlo del Supabase actual con
-- `pg_dump --schema-only` (o desde el dashboard) y pegarlo aquí.

-- ---------- RLS ----------
alter table public.participantes        enable row level security;
alter table public.codigos_participante enable row level security;
alter table public.quinielas            enable row level security;
alter table public.resultados_reales    enable row level security;
alter table public.configuracion        enable row level security;
alter table public.configuracion_visual enable row level security;

-- participantes: registro + login (lectura) + borrado admin
drop policy if exists "p_select" on public.participantes;
create policy "p_select" on public.participantes for select to anon using (true);
drop policy if exists "p_insert" on public.participantes;
create policy "p_insert" on public.participantes for insert to anon with check (true);
drop policy if exists "p_delete" on public.participantes;
create policy "p_delete" on public.participantes for delete to anon using (true);

-- codigos_participante
drop policy if exists "c_select" on public.codigos_participante;
create policy "c_select" on public.codigos_participante for select to anon using (true);
drop policy if exists "c_insert" on public.codigos_participante;
create policy "c_insert" on public.codigos_participante for insert to anon with check (true);
drop policy if exists "c_update" on public.codigos_participante;
create policy "c_update" on public.codigos_participante for update to anon using (true);
drop policy if exists "c_delete_libres" on public.codigos_participante;
create policy "c_delete_libres" on public.codigos_participante for delete to anon using (usado = false);

-- quinielas
drop policy if exists "q_select" on public.quinielas;
create policy "q_select" on public.quinielas for select to anon using (true);
drop policy if exists "q_insert" on public.quinielas;
create policy "q_insert" on public.quinielas for insert to anon with check (true);
drop policy if exists "q_update" on public.quinielas;
create policy "q_update" on public.quinielas for update to anon using (true);
drop policy if exists "q_delete" on public.quinielas;
create policy "q_delete" on public.quinielas for delete to anon using (true);

-- resultados_reales
drop policy if exists "r_select" on public.resultados_reales;
create policy "r_select" on public.resultados_reales for select to anon using (true);
drop policy if exists "r_insert" on public.resultados_reales;
create policy "r_insert" on public.resultados_reales for insert to anon with check (true);
drop policy if exists "r_update" on public.resultados_reales;
create policy "r_update" on public.resultados_reales for update to anon using (true);
drop policy if exists "r_delete" on public.resultados_reales;
create policy "r_delete" on public.resultados_reales for delete to anon using (true);

-- configuracion
drop policy if exists "cfg_select" on public.configuracion;
create policy "cfg_select" on public.configuracion for select to anon using (true);
drop policy if exists "cfg_insert" on public.configuracion;
create policy "cfg_insert" on public.configuracion for insert to anon with check (true);
drop policy if exists "cfg_update" on public.configuracion;
create policy "cfg_update" on public.configuracion for update to anon using (true);

-- configuracion_visual
drop policy if exists "cv_select" on public.configuracion_visual;
create policy "cv_select" on public.configuracion_visual for select to anon using (true);
drop policy if exists "cv_insert" on public.configuracion_visual;
create policy "cv_insert" on public.configuracion_visual for insert to anon with check (true);
drop policy if exists "cv_update" on public.configuracion_visual;
create policy "cv_update" on public.configuracion_visual for update to anon using (true);
drop policy if exists "cv_delete" on public.configuracion_visual;
create policy "cv_delete" on public.configuracion_visual for delete to anon using (true);

notify pgrst, 'reload schema';
